name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '31 1,12 * * *'

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout V DO
      uses: actions/checkout@v2
      with:
        path: vdo
    - name: Build V
      run: make
    - name: v vet
      run: ./v vet vdo
    - name: v fmt -verify
      run: ./v fmt -verify vdo

  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout V DO
      uses: actions/checkout@v2
      with:
        path: vdo
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --quiet -y libglfw3-dev libxi-dev libxcursor-dev
    - name: Build V
      run: |
        make
        sudo ./v symlink
    - name: Install UI
      run: v install ui
    - name: Build V DO
      run: |
        echo 'Build vdo with -prod'
        v -prod vdo

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout V DO
      uses: actions/checkout@v2
      with:
        path: vdo
    - name: Build V
      run: |
        make
        ./v symlink
    - name: Install UI
      run: v install ui
    - name: Build V DO
      run: |
        echo 'Build vdo with -prod'
        v -prod vdo
        v vdo

  windows-msvc:
    runs-on: windows-latest
    env:
        VFLAGS: -cc msvc
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout V DO
      uses: actions/checkout@v2
      with:
        path: vdo
    - name: Build V
      run: |
        .\make.bat -msvc
    # Don't move applying V directory to PATH, to other steps
    # otherwise this step and V script won't see V executable.
    - name: Build UI examples
      run: |
        echo 'Install UI'
        v install ui
        $env:path += ";$(get-location)"
        echo 'Build vdo with -prod'
        v -prod vdo
        echo "=========================="
        echo "v -showcc .\vdo"